### PR TITLE
fix: type of DraftHeadersVersion

### LINKED ISSUE #505: Incorrect type for DraftHeadersVersion
### Description

The type for `DraftHeadersVersion` is `string` rather than `"draft-6" | "draft-7" | "draft-8"`, this is because `SUPPORTED_DRAFT_VERSIONS` is defined as a string array rather than a const array

### Library version

7.5.0

### Node version

v22.14.0

### Typescript version (if you are using it)

5.2.2

### Module system

ESM

### PR DESCRIPTION
**Pull request by JasonMan34**
- closes #505

### CODE REVIEW

**Comment by nfriedly** [comment]
Thanks, appreciate the fix!

**Comment by nfriedly** [comment]
Does this change usage of the library at all, or only the internal testing / tslint stuff?

(In other words, do you think it merits a new release?)

File: test/library/options-test.ts [hunk 1]
```diff
@@ -95,4 +95,11 @@ describe('options test', () => {
 			})
 		}).toThrowError(/store/)
 	})
+
+	it('should not allow an invalid standardHeaders option', async () => {
+		rateLimit({
+			// @ts-expect-error Check correct typing of standardHeaders
+			standardHeaders: 'not-a-valid-draft',
+		})
+	})
```
Comment (gamemaker1) [inline test/library/options-test.ts:104]: This should be surrounded by an `expect(...).toThrow()` block.

**Review by gamemaker1 — COMMENTED** [review]
Hi,

I noticed that the added test is incomplete, but since it's already merged I'll make the change separately.

Thanks for the PR!

File: test/library/options-test.ts (hunk 1 above)
Comment (JasonMan34) [reply test/library/options-test.ts:104]: This is only a TypeScript test. Although to make it truly TypeScript-only it would need to be surrounded by an `if (false)` block or something.

The code doesn't currently check the value given on instantiation, only when the time actually comes to set the headers, so that code block doesn't currently throw.
I think it should throw actually, as there's no reason to wait if we know the value is wrong, but I didn't want to dive into the flow of the actual code, so I only made the type test

Comment (gamemaker1) [reply test/library/options-test.ts:104]: Ah okay I misunderstood it. We can keep it as-is, I'll just add a comment explaining that its a Typescript-only test then. Thanks!
